### ISSUE TITLE
Different basins raster output when running multipleflow  or  singleflow on jupyter notebook (  grass 8.4 dev version)

### ISSUE THREAD

**Issue by rengifoo** [ncsu-geoforall-lab/GIS714-assignments#31]
Hei Guys  !
First of all a big thanks for implementing the jupyter notebook for grass gis.  These days I have been experimenting with it and realised that the basin raster output differs quite a lot depending on which algorithm I am using. I tested it and is the same behavior within grass gis. I am unsure if it an issue of grass gis  or an issue on  how grass gis interacts with jupyter. Below is the command I use to run the r.watershed module within   jupyter notebook.

single flow
!r.watershed -sab --overwrite elevation=Romerike threshold=100000 basin=basin100k accumulation=flowacc100k drainage=flowdir100k stream=stream100k spi=spi100k
multiple flow
!r.watershed -ab --overwrite elevation=Romerike threshold=100000 basin=basin100k accumulation=flowacc100k drainage=flowdir100k stream=stream100k spi=spi100k

Hope to get some hints

Thanks in advance!
best regards
Rengifo Ortega

![singleFLOW](https://github.com/ncsu-geoforall-lab/GIS714-assignments/assets/92565915/54872760-d90e-4430-b544-ea546cb3d067)
![MultiFLOW](https://github.com/ncsu-geoforall-lab/GIS714-assignments/assets/92565915/a8c34040-8afe-4f62-8278-8b4cfff94b67)

**Comment by chaedri** [comment]
Hey Rengifo! Glad GRASS GIS is working well for you in Jupyter Notebooks. I suspect this is more to do with the internal workings of the r.watershed module than the grass.jupyter side of things. I've also seen this behavior in my own explorations with r.watershed and I'm not sure why it occurs or if it's expected behavior. I suggest you open an issue in the [GRASSS GIS github repo](https://github.com/OSGeo/grass) since someone there likely has a better explanation or will be able to fix it.

**Comment by rengifoo** [comment]
Thanks for your quick response. I will report it to grass gis github repo admin.

best regards
Rengifo Ortega
